"""empty message

Revision ID: 2bae165b62d8
Revises: ab98f9cd2b36
Create Date: 2024-08-22 19:05:23.661192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2bae165b62d8'
down_revision = 'ab98f9cd2b36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comparativas')
    with op.batch_alter_table('game_characteristics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stores_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'stores', ['stores_id'], ['id'])

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('price_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_column('price_date')
        batch_op.drop_column('price')

    with op.batch_alter_table('game_characteristics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('stores_id')

    op.create_table('comparativas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('offert_slug', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('price_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('stores_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('game_characteristic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['game_characteristic_id'], ['game_characteristics.id'], name='comparativas_game_characteristic_id_fkey'),
    sa.ForeignKeyConstraint(['stores_id'], ['stores.id'], name='comparativas_stores_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='comparativas_pkey')
    )
    # ### end Alembic commands ###
