"""empty message

Revision ID: 9748bd1c0fcb
Revises: 2bae165b62d8
Create Date: 2024-08-22 19:09:30.418390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9748bd1c0fcb'
down_revision = '2bae165b62d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_characteristics', schema=None) as batch_op:
        batch_op.drop_column('filetype')
        batch_op.drop_column('filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_characteristics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('filetype', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
